---

- name: apache | configure
  become: yes
  template:
    src:   virtualhost.j2
    dest:  "{{ apache_vhost_available }}/{{ item.servername }}.conf"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode:  0644
  register: __apache_vhost
  with_items: apache_virtual_hosts

- name: apache | check configuration
  become: yes
  template:
    src:      config-test.j2
    dest:     "/tmp/apache-configuration-validation"
    owner:    "{{ apache_user }}"
    group:    "{{ apache_group }}"
    mode:     0644
    validate: 'apachectl -t -f %s'
  ignore_errors: yes
  changed_when: false
  with_items: apache_virtual_hosts
  register: __apache_vhost_check
#  when: __apache_vhost.changed

- name: apache | remove configuration check file
  become: yes
  file:
    path: "/tmp/apache-configuration-validation"
    state: absent

- name: apache | remove invalid vhosts
  become: yes
  file:
    path: "{{ apache_vhost_available }}/{{ item.item.servername }}.conf"
    state: absent
  with_items: __apache_vhost_check.results
  when: item.failed

- name: apache | link valid vhosts
  become: yes
  file:
    src: "{{ apache_vhost_available }}/{{ item.item.servername }}.conf"
    dest: "{{ apache_vhost_enabled }}/{{ item.item.servername }}.conf"
    state: link
  with_items: __apache_vhost_check.results
  when: not item.failed
  notify: restart apache
